area/apps:
  - changed-files:
      - any-glob-to-any-file:
          - apps/**/*
          - include/**/*
area/github:
  - changed-files:
      - any-glob-to-any-file:
          - .github/**/*
area/mise:
  - changed-files:
      - any-glob-to-any-file:
          - .mise.toml
area/renovate:
  - changed-files:
      - any-glob-to-any-file:
          - .renovate/**/*
          - .renovaterc.json5
area/taskfile:
  - changed-files:
      - any-glob-to-any-file:
          - .taskfiles/**/*
          - Taskfile.yaml
app/bazarr:
  - changed-files:
      - any-glob-to-any-file:
          - apps/bazarr/**
app/prowlarr:
  - changed-files:
      - any-glob-to-any-file:
          - apps/prowlarr/**
app/qbittorrent:
  - changed-files:
      - any-glob-to-any-file:
          - apps/qbittorrent/**
app/sabnzbd:
  - changed-files:
      - any-glob-to-any-file:
          - apps/sabnzbd/**
app/radarr:
  - changed-files:
      - any-glob-to-any-file:
          - apps/radarr/**
app/plex:
  - changed-files:
      - any-glob-to-any-file:
          - apps/plex/**
app/tautulli:
  - changed-files:
      - any-glob-to-any-file:
          - apps/tautulli/**
app/it-tools:
  - changed-files:
      - any-glob-to-any-file:
          - apps/it-tools/**
app/smartctl-exporter:
  - changed-files:
      - any-glob-to-any-file:
          - apps/smartctl-exporter/**
app/caddy:
  - changed-files:
      - any-glob-to-any-file:
          - apps/caddy/**
app/sonarr:
  - changed-files:
      - any-glob-to-any-file:
          - apps/sonarr/**
